
networks: 
    db:

volumes:
    minio_data:

services: 

    ##########
    # Minio #
    # https://min.io/docs/minio/linux/index.html
    ##########
    # https://hub.docker.com/r/minio/minio
    # minioadmin:minioadmin
    minio:
        image: quay.io/minio/minio:latest
        container_name: minio
        restart: always
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - minio_data:/data
        ports: [9101:9001] # api, webui
        networks: [db]
        command: ['server', '/data', '--console-address', ":9001"]

    # MINIO CLIENT #
    minio_mc:
        image: quay.io/minio/minio:latest
        container_name: minio_mc
        restart: always
        volumes:
            - .:/var/www
        depends_on:
            - minio
        networks: [db]
        entrypoint: >
            /bin/sh -c "
                mc alias set myminio http://minio:9000 minioadmin minioadmin && sleep infinity
            "

    # ADMIN #
    # @https://min.io/docs/minio/linux/reference/minio-mc-admin.html