
networks: 
    db:

volumes:
    mongo_data:

services: 

    # docker run --name some-mongo -v /my/custom:/etc/mongo -d mongo --config /etc/mongo/mongod.conf

    #########
    # Mongo #
    #########
    mongo:
        image: mongo:8.0-rc
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass
        volumes:
            - .:/var/www
            - mongo_data:/data/db
        networks: [db]

    mongo-express:
        image: mongo-express
        restart: always
        ports: [8085:8081]
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: user
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017/
            ME_CONFIG_BASICAUTH: false
        networks: [db]
