# include:
#   - docker-compose-db.yaml
#   - docker-compose-kv.yaml

networks: 
    db:

services: 
    ubuntu: 
        build:
            context: .
        restart: always
        environment:
            - MYSQL_DSN=mysql:host=mysql;port=3306;dbname=mydb
        volumes:
            - .:/var/www/html
        command: sleep infinity
            # tail -f /dev/null
            # while true; do sleep 1; done
        networks: [db]