--
-- Generated by python
--
INSERT INTO `tree` (`name`, `type`, `size`)
VALUES ('Darren Johnson', 'fall', 776),
('Kathryn Davis', 'late', 127),
('Jamie Long', 'moment', 521),
('Amy Harris', 'economy', 241),
('Sandra Nguyen', 'them', 266),
('Maria Beard', 'never', 680),
('Robin Robinson', 'listen', 581),
('Brian White', 'themselves', 393),
('Jessica Brown', 'bank', 681),
('Dana Chang', 'best', 204)
;