import lib.common as libcommon
import lib.getfake as libgetfake


text = (
    "--\n-- Generated by python\n--\n"
    "INSERT INTO `tree` (`name`, `type`, `size`)\n" 
)
for _ in range(10):
    fake = libgetfake.generate_arr()
    val = 'VALUES ' if _ == 0 else ''
    hit = '' if _ == 9 else ','
    text += f"{val}('{fake['name']}', '{fake['word']}', {fake['int']}){hit}\n"
text += ';'

libcommon.append_file('mysql', 'mydb_data.sql', text)
